---
swagger: "2.0"
info:
  description: "API used to create delete and get opinion"
  version: "2022-11-12T17:01:49Z"
  title: "ManageOpinion"
host: "92p29q1nud.execute-api.us-east-1.amazonaws.com"
basePath: "/Development"
schemes:
- "https"
paths:
  /createopinion:
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "RequestCreateOpinion"
        required: true
        schema:
          $ref: "#/definitions/RequestCreateOpinion"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/ResponseCreateDeleteOpinion"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "500":
          description: "500 response"
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /deleteopinion:
    delete:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "RequestDeleteOpinion"
        required: true
        schema:
          $ref: "#/definitions/RequestDeleteOpinion"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/ResponseCreateDeleteOpinion"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "500":
          description: "500 response"
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /getopinion:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "region"
        in: "query"
        required: true
        type: "string"
      - name: "id"
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/ResponseGetOpinion"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "500":
          description: "500 response"
          schema:
            $ref: "#/definitions/ErrorResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
definitions:
  RequestCreateOpinion:
    type: "object"
    required:
    - "customerName"
    - "customerOpinion"
    - "messageIdentifier"
    - "region"
    properties:
      region:
        type: "string"
        description: "Region where the table is stored"
      customerName:
        type: "string"
        description: "Name of the user making the opinion"
      customerOpinion:
        type: "string"
        description: "opinion of the user"
      messageIdentifier:
        type: "string"
        description: "unique identifier of the opinion"
    title: "RequestCreateOpinion"
    description: "Create opinion request schema"
  ResponseCreateDeleteOpinion:
    type: "object"
    required:
    - "code"
    properties:
      code:
        type: "string"
        description: "http status code of the response"
    title: "ResponseCreateDeleteOpinion"
    description: "delete and create response schema"
  Empty:
    type: "object"
    title: "Empty Schema"
  ResponseGetOpinion:
    type: "object"
    required:
    - "Code"
    - "Item"
    properties:
      Code:
        type: "string"
        description: "http status code"
      Item:
        type: "object"
        description: "The opinion retrieved on the database"
        properties:
          CUSTOMER_OPINION:
            type: "string"
            description: "The opinion of the user"
          CUSTOMER_NAME:
            type: "string"
            description: "The name of the user who make the opinion"
          MESSAGE_IDENTIFIER:
            type: "string"
            description: "The id of the message"
    title: "ResponseGetOpinion"
    description: "Get opinion response schema"
  RequestDeleteOpinion:
    type: "object"
    required:
    - "id"
    - "region"
    properties:
      region:
        type: "string"
        description: "Region where the table is stored"
      id:
        type: "string"
        description: "unique identifier of the opinion"
    title: "RequestDeleteOpinion"
    description: "Delete opinion request schema"
  ErrorResponse:
    type: "object"
    required:
    - "error"
    - "message"
    - "name"
    properties:
      name:
        type: "string"
        description: "Name of the error"
      message:
        type: "string"
        description: "Description of the error"
      error:
        type: "object"
        description: "errorcode"
        properties:
          errorCode:
            type: "string"
            description: "http status error code"
    title: "ErrorResponse"
    description: "error response schema"
