---
swagger: "2.0"
info:
  description: "API used to manage the user appointments"
  version: "2023-05-28T23:11:01Z"
  title: "ManageUserAppointment"
host: "vr92308i2a.execute-api.us-east-1.amazonaws.com"
basePath: "/product"
schemes:
- "https"
paths:
  /deleteappointment:
    delete:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "requestDeleteUserAppointment"
        required: true
        schema:
          $ref: "#/definitions/requestDeleteUserAppointment"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/responsePutUpdateDeleteAppointment"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          schema:
            $ref: "#/definitions/errorResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "500":
          description: "500 response"
          schema:
            $ref: "#/definitions/errorResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      security:
      - api_key: []
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /getappointments:
    get:
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/responseGetUserAppointment"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          schema:
            $ref: "#/definitions/errorResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "500":
          description: "500 response"
          schema:
            $ref: "#/definitions/errorResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      security:
      - api_key: []
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /putappointment:
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "requestPutUserAppointment"
        required: true
        schema:
          $ref: "#/definitions/requestPutUserAppointment"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/responsePutUpdateDeleteAppointment"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          schema:
            $ref: "#/definitions/errorResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "500":
          description: "500 response"
          schema:
            $ref: "#/definitions/errorResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      security:
      - api_key: []
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /updateappointment:
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
    patch:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "requestUpdateAppointment"
        required: true
        schema:
          $ref: "#/definitions/requestUpdateAppointment"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/responsePutUpdateDeleteAppointment"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          schema:
            $ref: "#/definitions/responseGetUserAppointment"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "500":
          description: "500 response"
          schema:
            $ref: "#/definitions/errorResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  responsePutUpdateDeleteAppointment:
    type: "object"
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "string"
        description: "http status code"
      name:
        type: "string"
        description: "this is the name of the HTTP Status code"
      message:
        type: "string"
        description: "This is the message to show to the user if necessary"
    title: "Response Update - Delete - Bmi data"
    description: "schema for the response of the delete and update data"
  Empty:
    type: "object"
    title: "Empty Schema"
  requestPutUserAppointment:
    type: "object"
    required:
    - "data"
    - "id"
    - "region"
    properties:
      id:
        type: "string"
        description: "identifier of the user"
      region:
        type: "string"
        description: "region in which the table is deployed"
      data:
        type: "object"
        properties:
          profession:
            type: "string"
            description: "the one who is going to see you"
          date:
            type: "string"
            description: "date in wich the appointment is going to be"
          time:
            type: "string"
            description: "time of the appointment"
          status:
            type: "string"
            description: "status of the appointment (active or not active)"
          direction:
            type: "string"
            description: "where the appointment is going to be"
          description:
            type: "string"
            description: "description of the appointment"
          identifier:
            type: "string"
            description: "uuid identifier of the appointment data"
    title: "ResponseGetUserData"
    description: "get user appointment response schema"
  responseGetUserAppointment:
    type: "object"
    required:
    - "code"
    - "data"
    - "message"
    - "name"
    properties:
      name:
        type: "string"
        description: "name of the http status code"
      code:
        type: "string"
        description: "http status code"
      message:
        type: "string"
        description: "message to be presented if necessesary"
      data:
        type: "array"
        description: "array of bmi data"
        items:
          type: "object"
          properties:
            profession:
              type: "string"
              description: "the one who is going to see you"
            date:
              type: "string"
              description: "date in wich the appointment is going to be"
            time:
              type: "string"
              description: "time of the appointment"
            status:
              type: "string"
              description: "status of the appointment (active or not active)"
            direction:
              type: "string"
              description: "where the appointment is going to be"
            description:
              type: "string"
              description: "description of the appointment"
            identifier:
              type: "string"
              description: "uuid identifier of the appointment data"
    title: "ResponseGetUserData"
    description: "get user appointment response schema"
  requestDeleteUserAppointment:
    type: "object"
    required:
    - "id"
    - "region"
    properties:
      id:
        type: "string"
        description: "identifier of the user"
      region:
        type: "string"
        description: "region in which the table is deployed"
      Appoitnmentid:
        type: "string"
        description: "identifier of the appointment entry to be deleted"
    title: "ResponseGetUserData"
    description: "get user appointment response schema"
  requestUpdateAppointment:
    type: "object"
    required:
    - "Appoitnment"
    - "Appoitnmentid"
    - "id"
    - "region"
    properties:
      id:
        type: "string"
        description: "identifier of the user"
      region:
        type: "string"
        description: "region in which the table is deployed"
      Appoitnmentid:
        type: "string"
        description: "identifier of the appointment to be updated"
      Appoitnment:
        type: "object"
        properties:
          profession:
            type: "string"
            description: "the one who is going to see you"
          date:
            type: "string"
            description: "date in wich the appointment is going to be"
          time:
            type: "string"
            description: "time of the appointment"
          status:
            type: "string"
            description: "status of the appointment (active or not active)"
          direction:
            type: "string"
            description: "where the appointment is going to be"
          description:
            type: "string"
            description: "description of the appointment"
          identifier:
            type: "string"
            description: "uuid identifier of the appointment data"
    title: "ResponseGetUserData"
    description: "update the appointment schema"
  errorResponse:
    type: "object"
    required:
    - "error"
    - "message"
    - "name"
    properties:
      name:
        type: "string"
        description: "Name of the error"
      message:
        type: "string"
        description: "Description of the error"
      user_message:
        type: "string"
        description: "Message error to show to the user"
      error:
        type: "object"
        description: "errorcode"
        properties:
          errorCode:
            type: "string"
            description: "http status error code"
          TypeOfError:
            type: "string"
            description: "If the error is a thecnical error or an 8 layer error"
    title: "ErrorResponse"
    description: "error response schema"
