name: Email Template Push
run-name: push meant to run when the email templates are push
on:
  push:
    branches:
      - master
    paths:
      - 'Email-Templates/**'
      - '!Email-Templates/README.md'
      - '!Email-Templates/metaData.txt'
jobs:
  publish_template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.KEY_ID }}
          aws-secret-access-key: ${{ secrets.KEY_PASS }}
          aws-region: ${{ secrets.REGION }}

      - name: "Download npm"
        run: |
          sudo apt update
          sudo apt install npm

      - name: "download dependencies"
        working-directory: ./Email-Templates/script/
        run: |
          npm install

      - name: "run script that creates the templates"
        working-directory: ./Email-Templates/
        run: |
          node ./script/create-templates.mjs