name: Email Template Push
run-name: push meant to run when the email templates are push
on:
  push:
    branches:
      - master
    paths:
      - 'Email-Templates/**'
      - '!Email-Templates/README.md'
jobs:
  publish_template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.KEY_ID }}
          aws-secret-access-key: ${{ secrets.KEY_PASS }}
          aws-region: ${{ secrets.REGION }}
      
      - name: "create templates on AWS"
        working-directory: ./Email-Templates/
        run: |
          input="metaData.txt"
          while read templateName subjectName templateFileNameHTML templateFileNameTEXT
            do
              directory=`pwd`
              htmlValue= `cat pwd${templateFileNameHTML}`
              textValue= `cat pwd${templateFileNameTEXT}`
              subjectnameValue= $(echo $subjectName | tr "_" " ")
              json = "{
                \"Template\": {
                \"TemplateName\": \"$templateName\",
                \"SubjectPart\": \"$subjectnameValue\",
                \"TextPart\": \"$textValue\",
                \"HtmlPart\": \"$htmlValue\"
                              }
                      }"
              echo $json > deployConfiguration.json
              aws ses create-template --cli-input-json deployConfiguration.json 
          done < "$input"