name: Web Push
run-name: push meant to run when the web page is modified
on:
  push:
    branches:
      - master
    paths:
      - Web-Page/**

jobs:
  publishPage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Download npm"
        run: |
          sudo apt update
          sudo apt install npm
      
      - name: "Download dependencies"
        working-directory: ./Web-Page/
        run: |
          npm install

      - name: "Create dotenv file"
        working-directory: ./Web-Page/
        run: |
          touch .env
          echo REACT_APP_DATA_URL=${{ secrets.DATA_URL }}>>.env
          echo REACT_APP_APPOINTMENTS_URL=${{ secrets.APPOINTMENTS_URL }}>>.env
          echo REACT_APP_USER_URL=${{ secrets.USER_URL }}>>.env
          echo REACT_APP_OPINION_URL=${{ secrets.OPINION_URL }}>>.env
          echo REACT_APP_APIKEY=${{ secrets.APIKEY }}>>.env

      - name: "echo ls"
        working-directory: ./Web-Page/
        run: |
          echo ls


      - name: "Prepare build of artifacts"
        working-directory: ./Web-Page/
        run: npm run build
      
      - name: "Set credentials for AWS"
        run: |
          aws configure set aws_access_key_id ${{ secrets.KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.KEY_PASS }}
          aws configure set region ${{ secrets.REGION }}
      
      - name: "Upload the artifacts to AWS S3"
        working-directory: ./Web-Page
        env:
          BUCKET_NAME: "webbmistoreapplication"
          FOLDER_PATH: "/"
        run: |
          aws s3 cp ./build/ s3://$BUCKET_NAME$FOLDER_PATH --recursive