name: Web Push
run-name: push meant to run when the web page is modified
on:
  push:
    branches:
      - master
    paths:
      - Web-Page/**

jobs:
  publishPage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.REGION }}
          aws-access-key-id: ${{ secrets.KEY_ID }}
          aws-secret-access-key: ${{ secrets.KEY_ID }}
          
      - name: "Download npm"
        run: |
          sudo apt update
          sudo apt install npm
      
      - name: "Download dependencies"
        working-directory: ./Web-Page/
        run: |
          npm install

      - name: "Prepare build of artifacts"
        working-directory: ./Web-Page/
        env:
          DATA_URL: ${{ secrets.DATA_URL }}
          APPOINTMENTS_URL: ${{ secrets.APPOINTMENTS_URL }}
          USER_URL: ${{ secrets.USER_URL }}
          OPINION_URL: ${{ secrets.OPINION_URL }}
          APIKEY: ${{ secrets.APIKEY }}
        run: npm run build

      - name: "Upload the artifacts to AWS S3"
        working-directory: ./Web-Page
        env:
          BUCKET_NAME: "webbmistoreapplication"
          FOLDER_PATH: "/"
        run: |
          aws s3 cp /build/ s3://$BUCKET_NAME$FOLDER_PATH --recursive