name: Web Push
run-name: push meant to run when the web page is modified
on:
  push:
    branches:
      - master
    paths:
      - 'Web-Page/**'
      - '!Web-Page/README.md'

jobs:
  publishPage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.KEY_ID }}
          aws-secret-access-key: ${{ secrets.KEY_PASS }}
          aws-region: ${{ secrets.REGION }}

      - name: "Download npm"
        run: |
          sudo apt update
          sudo apt install npm
      
      - name: "Download dependencies"
        working-directory: ./Web-Page/
        run: |
          npm install

      - name: "Create dotenv file"
        working-directory: ./Web-Page/
        run: |
          touch .env
          echo REACT_APP_DATA_URL=${{ secrets.DATA_URL }}>>.env
          echo REACT_APP_APPOINTMENTS_URL=${{ secrets.APPOINTMENTS_URL }}>>.env
          echo REACT_APP_USER_URL=${{ secrets.USER_URL }}>>.env
          echo REACT_APP_OPINION_URL=${{ secrets.OPINION_URL }}>>.env
          echo REACT_APP_APIKEY=${{ secrets.APIKEY }}>>.env

      - name: "Prepare build of artifacts"
        working-directory: ./Web-Page/
        run: npm run build
      
      - name: "Upload the artifacts to AWS S3"
        working-directory: ./Web-Page
        env:
          BUCKET_NAME: "webbmistoreapplication"
          FOLDER_PATH: "/"
        run: |
          aws s3 cp ./build/ s3://$BUCKET_NAME$FOLDER_PATH --recursive

      - name: "Create an invalidation for cloudfront"
        working-directory: ./Web-Page
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"